### ISSUE TITLE
Failed to load xyz.maubot.reminder

### ISSUE THREAD

**Issue by MelBourbon** [maubot/reminder#15]
When starting a instance with plugin reminder I receive `internal server error` message in webinterface and the following log entries. Is this related to maubot or the reminder plugin?
```
[ERROR@maubot.loader.zip] Failed to load xyz.maubot.reminder v0.2.1
Traceback (most recent call last):
  File "/opt/maubot/lib/python3.6/site-packages/maubot/loader/zip.py", line 191, in _load
    importer.load_module(module)
  File "/opt/maubot/lib/python3.6/site-packages/maubot/lib/zipimport.py", line 282, in load_module
    exec(code, mod.__dict__)
  File "/opt/maubot/plugins/xyz.maubot.reminder-v0.2.1.mbp/reminder/__init__.py", line 1, in <module>
    from .bot import ReminderBot
  File "/opt/maubot/plugins/xyz.maubot.reminder-v0.2.1.mbp/reminder/bot.py", line 21, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/lib/python3.6/site-packages/maubot/loader/zip.py", line 176, in load
    return self._load(reset_cache)
  File "/opt/maubot/lib/python3.6/site-packages/maubot/loader/zip.py", line 195, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module reminder
[2020-08-15 21:45:00,776] [ERROR@maubot.server] Error in handler
Traceback (most recent call last):
  File "/opt/maubot/lib/python3.6/site-packages/maubot/loader/zip.py", line 191, in _load
    importer.load_module(module)
  File "/opt/maubot/lib/python3.6/site-packages/maubot/lib/zipimport.py", line 282, in load_module
    exec(code, mod.__dict__)
  File "/opt/maubot/plugins/xyz.maubot.reminder-v0.2.1.mbp/reminder/__init__.py", line 1, in <module>
    from .bot import ReminderBot
  File "/opt/maubot/plugins/xyz.maubot.reminder-v0.2.1.mbp/reminder/bot.py", line 21, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/lib/python3.6/site-packages/maubot/management/api/middleware.py", line 43, in error
    return await handler(request)
  File "/opt/maubot/lib/python3.6/site-packages/maubot/management/api/instance.py", line 87, in update_instance
    return await _update_instance(instance, data)
  File "/opt/maubot/lib/python3.6/site-packages/maubot/management/api/instance.py", line 71, in _update_instance
    await instance.update_started(data.get("started", None))
  File "/opt/maubot/lib/python3.6/site-packages/maubot/instance.py", line 269, in update_started
    await (self.start() if started else self.stop())
  File "/opt/maubot/lib/python3.6/site-packages/maubot/instance.py", line 162, in start
    cls = await self.loader.load()
  File "/opt/maubot/lib/python3.6/site-packages/maubot/loader/zip.py", line 176, in load
    return self._load(reset_cache)
  File "/opt/maubot/lib/python3.6/site-packages/maubot/loader/zip.py", line 195, in _load
raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module reminder
```

**Comment by G2G2G2G** [comment]
"ModuleNotFoundError: No module named 'pytz'"
did you try pip / pip3 install pytz ?????
