### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'remove'

### ISSUE THREAD

**Issue by promasu** [maubot/reminder#7]
When using `!reminder cancel` the above written error occurs

**Comment by UndeadKernel** [comment]
I'm experiencing a similar issue.
This is the traceback:

```python
Traceback (most recent call last):
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 132, in __parse_args__
    raise ValueError("Argument required")
ValueError: Argument required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/mautrix/client/client.py", line 189, in dispatch_manual_event
    await handler(data)
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 97, in __call__
    ok, res = await self.__call_subcommand__(evt, call_args, remaining_val)
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 122, in __call_subcommand__
    remaining_val=remaining_val)
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 101, in __call__
    ok, remaining_val = await self.__parse_args__(evt, call_args, remaining_val)
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 137, in __parse_args__
    await evt.reply(self.__mb_usage__)
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 191, in __mb_usage__
    return self.__mb_usage_without_subcommands__
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 185, in __mb_usage_without_subcommands__
    return f"**Usage:** {self.__mb_prefix__} {self.__mb_usage_args__}"
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 166, in __mb_prefix__
    return f"{self.__mb_parent__.__mb_prefix__} {self.__mb_name__}"
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 167, in __mb_prefix__
    return f"!{self.__mb_name__}"
  File "/opt/matrix-bots/maubot/lib/python3.6/site-packages/maubot/handlers/command.py", line 161, in __mb_name__
    return self.__mb_get_name__(self.__bound_instance__)
  File "/opt/matrix-bots/maubot/plugins/xyz.maubot.reminder-v0.1.0.mbp/reminder/bot.py", line 103, in <lambda>
    @command.new(name=lambda self: self.base_command,
AttributeError: 'NoneType' object has no attribute 'base_command'
```

**Comment by tulir** [comment]
The cancel command isn't properly supported, use redactions instead (remove the command you created the reminder with or the reaction you used to "subscribe" to another user's reminder)

**Comment by UndeadKernel** [comment]
Thanks for the reply!
Would it then make sense to remove the "cancel" command altogether then?
